/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated/diagnostics'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedFarmerRouteImport } from './routes/_authenticated/farmer'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated/fleet'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicTelemetryRouteImport } from './routes/api/public/telemetry'
import { Route as ApiPublicTranscribeRouteImport } from './routes/api/public/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFarmerRoute = AuthenticatedFarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelemetryRoute = ApiPublicTelemetryRouteImport.update({
  id: '/api/public/telemetry',
  path: '/api/public/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranscribeRoute = ApiPublicTranscribeRouteImport.update({
  id: '/api/public/transcribe',
  path: '/api/public/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/health': typeof HealthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/farmer': typeof AuthenticatedFarmerRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/health': typeof HealthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/farmer': typeof AuthenticatedFarmerRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/health': typeof HealthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/driver': typeof AuthenticatedDriverRoute
  '/_authenticated/farmer': typeof AuthenticatedFarmerRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/health'
    | '/admin'
    | '/diagnostics'
    | '/driver'
    | '/farmer'
    | '/fleet'
    | '/api/public/health'
    | '/api/public/telemetry'
    | '/api/public/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/health'
    | '/admin'
    | '/diagnostics'
    | '/driver'
    | '/farmer'
    | '/fleet'
    | '/api/public/health'
    | '/api/public/telemetry'
    | '/api/public/transcribe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/health'
    | '/_authenticated/admin'
    | '/_authenticated/diagnostics'
    | '/_authenticated/driver'
    | '/_authenticated/farmer'
    | '/_authenticated/fleet'
    | '/api/public/health'
    | '/api/public/telemetry'
    | '/api/public/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HealthRoute: typeof HealthRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicTelemetryRoute: typeof ApiPublicTelemetryRoute
  ApiPublicTranscribeRoute: typeof ApiPublicTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostics': {
      id: '/_authenticated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farmer': {
      id: '/_authenticated/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof AuthenticatedFarmerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telemetry': {
      id: '/api/public/telemetry'
      path: '/api/public/telemetry'
      fullPath: '/api/public/telemetry'
      preLoaderRoute: typeof ApiPublicTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transcribe': {
      id: '/api/public/transcribe'
      path: '/api/public/transcribe'
      fullPath: '/api/public/transcribe'
      preLoaderRoute: typeof ApiPublicTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDiagnosticsRoute: typeof AuthenticatedDiagnosticsRoute
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRoute
  AuthenticatedFarmerRoute: typeof AuthenticatedFarmerRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDiagnosticsRoute: AuthenticatedDiagnosticsRoute,
  AuthenticatedDriverRoute: AuthenticatedDriverRoute,
  AuthenticatedFarmerRoute: AuthenticatedFarmerRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HealthRoute: HealthRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicTelemetryRoute: ApiPublicTelemetryRoute,
  ApiPublicTranscribeRoute: ApiPublicTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
